title: Skyrift
description: Jeu d'action en python dans un univers peuplé de dragons
author: LIGNIER Noémie GERME Charlotte FAILLIE Chloé CHATELAIN Lilou ARABAH Yanis
download : true
remote_theme: just-the-docs/just-the-docs
footer: false


# last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
# last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

back_to_top: true
back_to_top_text: "Retour en haut"

search_enabled: true
color_scheme : green