site_name: Skyrift Documentation
repo_url: "https://github.com/nomimie16/skyrift"
site_url: https://nomimie16.github.io/skyrift/
use_directory_urls: true

nav:
  - Accueil: index.md
  # - Présentation: presentation.md
  - Installation: installation.md
  - Règles et fonctionnement: rules.md
  - Unités: entities.md
  - Structures: structures.md
  - Economie: economy.md
  - Gameplay & Stratégie: gameplay_strategie.md
  - FAQ: faq.md
  - Crédits: credits.md
  - Documentation technique:
      - Changelog: technique/changelog.md
      - Structure du projet: technique/structure.md
      - Dépendances: technique/dependencies.md
      - Paramètres: technique/settings.md
      - Maintenance et support: technique/support.md
      - Annexe : technique/annex.md


extra_css:
  - overrides/theme.css

theme:
  name: shadcn
  logo : assets/img/bourse.png
  color_mode: light

markdown_extensions:
  - pymdownx.blocks.tab
  - pymdownx.tabbed
  - codehilite
  - admonition
  - pymdownx.blocks.details